#!/bin/sh
#
# ufetch-osx - tiny system info for void
#

## INFO

# user is already defined
HOST="$(hostname)"
OS="macOS Sierra"
KERNEL="$(uname -sr)"
UPTIME="$(echo $(uptime) | cut -d' ' -f 3) min"
PACKAGES="$(echo $(brew info) | cut -d" " -f 3)"

## DEFINE COLORS

# probably don't change these
bc="$(tput bold)"	# bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"	# reset

# you can change these
lc="${bc}${c6}"		# labels
nc="${bc}${c6}"		# user and hostname
tc="${bc}${c7}"		# text
fc="${bc}${c2}"		# first color
sc="${c6}"		# second color

## OUTPUT

cat <<EOF
${c6}       /_\           ${nc}${USER}${tc}@${nc}${HOST}${rc}
${c7}      /   \          ${lc}OS:        ${tc}${OS}${rc}
${c7}     /     \ ${c6}/_\     ${lc}KERNEL:    ${tc}${KERNEL}${rc}
${c7}    /   ${c6}/_\\${c7} /   \    ${lc}UPTIME:    ${tc}${UPTIME}${rc}
${c7}   /   /   /     \   ${lc}PACKAGES:  ${tc}${PACKAGES}${rc}
${c7}  /___/___/_______\  ${lc}SHELL:     ${tc}${SHELL}${rc}

EOF
